### ISSUE TITLE
is it possible to 'identify' a user with this library?

### ISSUE THREAD

**Issue by andrewljohnson** [analytics-pros/universal-analytics-python#17]
I was wondering if it's possible to do 'identify' similar to how you'd do it on iOS with this library:

    id<GAITracker> tracker = [[GAI sharedInstance] defaultTracker];
    [tracker set:kGAIUserId value:userId];

Any help is much appreciated!

**Comment by samba** [comment]
@andrewljohnson  The tracker's constructor accepts a `user_id` parameter. 

Example:

```python
from UniversalAnalytics import Tracker
tracker = Tracker.create(ga_property_id, user_id="<user ident>")
```

(Though I'm the original author of this code, I'm no longer a maintainer. @LukaData may be the best contact going forward.)

**Comment by andrewljohnson** [comment]
Thanks, i did eventually figure that out :)
